#!/bin/bash

echo -e "[file manager] \t ranger mc"
echo -e "[web browser] \t surf qutebrowser firefox"
echo -e "[wifi config] \t nmtui"
echo -e "[youtube] \t\t yt"
echo -e "[sys monitor] \t htop bpytop"
echo -e "[clock] \t\t tty-clock"
echo -e "[disk usage] \t ncdu"
echo -e "[calculator] \t bc"
echo -e "[sytem info] \t neofetch"
echo -e "[text editor] \t micro nano nvim"
echo -e "[file fimder] \t fzf"
echo -e "[help] \t\t\t tldr"
echo -e "[net utility] \t speedtest-cli fping"
echo -e "[web search] \t ddgr googler rtv"
echo -e "[calendar] \t\t khal"
echo -e "[email] \t\t mutt"
echo -e "[ascii] \t\t figlet lolcat cowsay jp2a"
