#!/bin/bash

echo -e "[file manager] \t ranger (mc nnn)"
echo -e "[web browser] \t surf  (qutebrowser firefox)"
echo -e "[wifi config] \t nmtui"
echo -e "[youtube] \t\t yt"
echo -e "[sys monitor] \t btop (htop bpytop)"
echo -e "[clock] \t\t tty-clock"
echo -e "[disk usage] \t ncdu gdu"
echo -e "[calculator] \t bc"
echo -e "[sytem info] \t neofetch"
echo -e "[text editor] \t nvim wordgrinder (micro nano)"
echo -e "[file fimder] \t fzf"
echo -e "[help] \t\t\t tldr"
echo -e "[net utility] \t speedtest-cli fping"
echo -e "[web search] \t ddgr googler"
echo -e "[calendar] \t\t khal"
echo -e "[email] \t\t neomutt (mutt)"
echo -e "[ascii] \t\t figlet lolcat cowsay jp2a"
echo -e "[fun] \t\t espeak hollywood cmatrix"
echo -e "[git] \t\t tig gita"
